### PR TITLE
Updated parser

### PR DESCRIPTION
**Pull request by codenstory**
now you don't need to spacing tokens

### CODE REVIEW

**Comment by RedoC-github** [comment]
Started to check

**Comment by RedoC-github** [comment]
I think you didn't code about the first whitespace in line of code.

**Comment by RedoC-github** [comment]
wait a sec... you made code about that error...

**Comment by RedoC-github** [comment]
@codenstory I fixed. 🎉

**Review by RedoC-github — APPROVED** [review]
Working Well 🎉

**Comment by codenstory** [comment]
Thank you !

**Pull request merged**
